/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonAppearance, ButtonContent } from "./components/dora-button/dora-button";
export { ButtonAppearance, ButtonContent } from "./components/dora-button/dora-button";
export namespace Components {
    interface DoraButton {
        /**
          * 外观
         */
        "appearance"?: ButtonAppearance;
        /**
          * 内容
         */
        "content"?: ButtonContent;
    }
}
declare global {
    interface HTMLDoraButtonElement extends Components.DoraButton, HTMLStencilElement {
    }
    var HTMLDoraButtonElement: {
        prototype: HTMLDoraButtonElement;
        new (): HTMLDoraButtonElement;
    };
    interface HTMLElementTagNameMap {
        "dora-button": HTMLDoraButtonElement;
    }
}
declare namespace LocalJSX {
    interface DoraButton {
        /**
          * 外观
         */
        "appearance"?: ButtonAppearance;
        /**
          * 内容
         */
        "content"?: ButtonContent;
    }
    interface IntrinsicElements {
        "dora-button": DoraButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dora-button": LocalJSX.DoraButton & JSXBase.HTMLAttributes<HTMLDoraButtonElement>;
        }
    }
}
