/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DoraButton {
        /**
          * 容器class
         */
        "containerClass"?: string;
        /**
          * 文本
         */
        "label"?: string;
        /**
          * 文本class
         */
        "labelClass"?: string;
    }
}
declare global {
    interface HTMLDoraButtonElement extends Components.DoraButton, HTMLStencilElement {
    }
    var HTMLDoraButtonElement: {
        prototype: HTMLDoraButtonElement;
        new (): HTMLDoraButtonElement;
    };
    interface HTMLElementTagNameMap {
        "dora-button": HTMLDoraButtonElement;
    }
}
declare namespace LocalJSX {
    interface DoraButton {
        /**
          * 容器class
         */
        "containerClass"?: string;
        /**
          * 文本
         */
        "label"?: string;
        /**
          * 文本class
         */
        "labelClass"?: string;
    }
    interface IntrinsicElements {
        "dora-button": DoraButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dora-button": LocalJSX.DoraButton & JSXBase.HTMLAttributes<HTMLDoraButtonElement>;
        }
    }
}
